export const ERRORS = {
  "email taken": "Введённый Email уже занят",
  "logged out": "Для доступа к системе необходима авторизация",
  "team cannot contain email address":
    "Название команды не может содержать email адрес",
  "email doesn't exist": "Email не существует",
  "annotation name taken": "Название аннотации уже занято",
  "annotation not found": "Аннотация не найдена",
  "nomination event does not exist": "Компетенция не существует",
  "nomination event already exist": "Компетенция уже существует",
  "tournament started": "Турнир уже начался",
  "tournament not started": "Турнир ещё не начался",
  "participant not in nomination event": "Участник не зарегистрирован на данную компетенцию",
  "registration finished": "Регистрация завершена",
  "participant already in nomination event": "Участник уже зарегистрирован на данную компетенцию",
  "you are not in judge command": "Вы не входите в судейский состав",
  "race round length should be at least 1": "Длина раунда должна быть не менее 1",
  "race tournament finished": "Турнир завершён",
  "criterias names has duplicates": "Названия критериев содержат дубликаты",
  "criteria not found": "Критерий не найден",
  "criteria not in nomination event": "Критерий не относится к событию номинации",
  "not all criterias set": "Не все критерии установлены",
  "can not decrypt password": "Невозможно расшифровать пароль",
  "equipment not found": "Оборудование не найдено",
  "event name taken": "Название мероприятия уже занято",
  "event does not exist": "Мероприятие не существует",
  "this event is not yours": "Это мероприятие вам не принадлежит",
  "invalid json": "Некорректный JSON",
  "invalid event id": "Некорректный идентификатор мероприятия",
  "invalid file extension": "Недопустимое расширение файла",
  "file is too large": "Файл слишком велик",
  "match not related to group": "Матч не связан с группой",
  "match not found": "Матч не найден",
  "team not related to match": "Команда не связана с матчем",
  "prev matches not finished": "Предыдущие матчи не завершены",
  "nomination not found": "Компетенция не найдена",
  "nomination name taken": "Название компетенции уже занято",
  "you cannot delete owner": "Вы не можете удалить владельца",
  "email taken error": "Введённый Email уже занят",
  "participant does not exist": "Участник не существует",
  "participant does not belongs to owner": "Участник не принадлежит владельцу",
  "race round not found": "Раунд гонки не найден",
  "software not found": "Программное обеспечение не найдено",
  "team name taken": "Название команды уже занято",
  "team not found": "Команда не найдена",
  "this team is not yours": "Эта команда вам не принадлежит",
  "you cant not name team as default": "Вы не можете назвать команду как 'по умолчанию'",
  "default team is unchangeable": "Команда по умолчанию не может быть изменена",
  "team not in event nomination error": "Команда не участвует в компетенции",
  "participant already in team": "Участник уже состоит в команде",
  "participant not in team": "Участник не состоит в команде",
  "participant present more then one time": "Участник присутствует более одного раза",
  "Token expired, you are currently logged out": "Срок действия токена истёк, вы вышли из системы",
  "Token signature error, invalid token": "Ошибка подписи токена, недействительный токен",
  "Token does not exist": "Токен не существует",
  "Token is invalid": "Токен недействителен",
  "invalid group count": "Неверное количество групп",
  "not all matches are finished": "Не все матчи завершены",
  "group stage is not finished": "Групповой этап не завершён",
  "group stage is finished": "Групповой этап завершён",
  "wrong teams provided": "Предоставлены неверные команды",
  "play off stage already started": "Этап плей-офф уже начался",
  "play off stage already finished": "Этап плей-офф уже завершён",
  "play off stage not started": "Этап плей-офф не начался",
  "not all race_rounds_finished": "Не все раунды турнира по времени завершены",
  "criteria stage finished": "Этап критериев завершён",
  "invalid password": "Неверный пароль",
  "user not found": "Пользователь не найден",
  "you are not allowed to perform this action": "Вам не разрешено выполнять это действие",
  "passwords dont match": "Пароли не совпадают",
  "current password is missed": "Текущий пароль отсутствует",
  "one or more judges presented in judges_ids not found": "Один или несколько указанных судей не найдены",

  getError: function (errorKey) {
    return this[errorKey] || "Произошла неизвестная ошибка.";
  },
};
