import i18n from "@/translations/translations";

export const ERRORS = {
  "email taken": "ERRORS.EMAIL_TAKEN",
  "logged out": "ERRORS.LOGGED_OUT",
  "team cannot contain email address":
    "ERRORS.TEAM_CANNOT_CONTAIN_EMAIL_ADDRESS",
  "email doesn't exist": "ERRORS.EMAIL_DOES_NOT_EXIST",
  "annotation name taken": "ERRORS.ANNOTATION_NAME_TAKEN",
  "annotation not found": "ERRORS.ANNOTATION_NOT_FOUND",
  "nomination event does not exist": "ERRORS.NOMINATION_EVENT_DOES_NOT_EXIST",
  "nomination event already exist": "ERRORS.NOMINATION_EVENT_ALREADY_EXIST",
  "tournament started": "ERRORS.TOURNAMENT_STARTED",
  "tournament not started": "ERRORS.TOURNAMENT_NOT_STARTED",
  "participant not in nomination event":
    "ERRORS.PARTICIPANT_NOT_IN_NOMINATION_EVENT",
  "registration finished": "ERRORS.REGISTRATION_FINISHED",
  "participant already in nomination event":
    "ERRORS.PARTICIPANT_ALREADY_IN_NOMINATION_EVENT",
  "you are not in judge command": "ERRORS.YOU_ARE_NOT_IN_JUDGE_COMMAND",
  "race round length should be at least 1":
    "ERRORS.RACE_ROUND_LENGTH_SHOULD_BE_AT_LEAST_1",
  "race tournament finished": "ERRORS.RACE_TOURNAMENT_FINISHED",
  "criterias names has duplicates": "ERRORS.CRITERIAS_NAMES_HAS_DUPLICATES",
  "criteria not found": "ERRORS.CRITERIA_NOT_FOUND",
  "criteria not in nomination event": "ERRORS.CRITERIA_NOT_IN_NOMINATION_EVENT",
  "not all criterias set": "ERRORS.NOT_ALL_CRITERIAS_SET",
  "can not decrypt password": "ERRORS.CAN_NOT_DECRYPT_PASSWORD",
  "equipment not found": "ERRORS.EQUIPMENT_NOT_FOUND",
  "event name taken": "ERRORS.EVENT_NAME_TAKEN",
  "event does not exist": "ERRORS.EVENT_DOES_NOT_EXIST",
  "this event is not yours": "ERRORS.THIS_EVENT_IS_NOT_YOURS",
  "invalid json": "ERRORS.INVALID_JSON",
  "invalid event id": "ERRORS.INVALID_EVENT_ID",
  "invalid file extension": "ERRORS.INVALID_FILE_EXTENSION",
  "file is too large": "ERRORS.FILE_IS_TOO_LARGE",
  "match not related to group": "ERRORS.MATCH_NOT_RELATED_TO_GROUP",
  "match not found": "ERRORS.MATCH_NOT_FOUND",
  "team not related to match": "ERRORS.TEAM_NOT_RELATED_TO_MATCH",
  "prev matches not finished": "ERRORS.PREV_MATCHES_NOT_FINISHED",
  "nomination not found": "ERRORS.NOMINATION_NOT_FOUND",
  "nomination name taken": "ERRORS.NOMINATION_NAME_TAKEN",
  "you cannot delete owner": "ERRORS.YOU_CANNOT_DELETE_OWNER",
  "email taken error": "ERRORS.EMAIL_TAKEN_ERROR",
  "participant does not exist": "ERRORS.PARTICIPANT_DOES_NOT_EXIST",
  "participant does not belongs to owner":
    "ERRORS.PARTICIPANT_DOES_NOT_BELONG_TO_OWNER",
  "race round not found": "ERRORS.RACE_ROUND_NOT_FOUND",
  "software not found": "ERRORS.SOFTWARE_NOT_FOUND",
  "team name taken": "ERRORS.TEAM_NAME_TAKEN",
  "team not found": "ERRORS.TEAM_NOT_FOUND",
  "this team is not yours": "ERRORS.THIS_TEAM_IS_NOT_YOURS",
  "you cant not name team as default":
    "ERRORS.YOU_CANT_NOT_NAME_TEAM_AS_DEFAULT",
  "default team is unchangeable": "ERRORS.DEFAULT_TEAM_IS_UNCHANGEABLE",
  "team not in event nomination error":
    "ERRORS.TEAM_NOT_IN_EVENT_NOMINATION_ERROR",
  "participant already in team": "ERRORS.PARTICIPANT_ALREADY_IN_TEAM",
  "participant not in team": "ERRORS.PARTICIPANT_NOT_IN_TEAM",
  "participant present more then one time":
    "ERRORS.PARTICIPANT_PRESENT_MORE_THAN_ONE_TIME",
  "token expired, you are currently logged out": "ERRORS.TOKEN_EXPIRED",
  "token signature error, invalid token": "ERRORS.TOKEN_SIGNATURE_ERROR",
  "token does not exist": "ERRORS.TOKEN_DOES_NOT_EXIST",
  "token is invalid": "ERRORS.TOKEN_IS_INVALID",
  "invalid group count": "ERRORS.INVALID_GROUP_COUNT",
  "not all matches are finished": "ERRORS.NOT_ALL_MATCHES_ARE_FINISHED",
  "group stage is not finished": "ERRORS.GROUP_STAGE_IS_NOT_FINISHED",
  "group stage is finished": "ERRORS.GROUP_STAGE_IS_FINISHED",
  "wrong teams provided": "ERRORS.WRONG_TEAMS_PROVIDED",
  "play off stage already started": "ERRORS.PLAY_OFF_STAGE_ALREADY_STARTED",
  "play off stage already finished": "ERRORS.PLAY_OFF_STAGE_ALREADY_FINISHED",
  "play off stage not started": "ERRORS.PLAY_OFF_STAGE_NOT_STARTED",
  "not all race_rounds_finished": "ERRORS.NOT_ALL_RACE_ROUNDS_FINISHED",
  "criteria stage finished": "ERRORS.CRITERIA_STAGE_FINISHED",
  "invalid password": "ERRORS.INVALID_PASSWORD",
  "user not found": "ERRORS.USER_NOT_FOUND",
  "you are not allowed to perform this action":
    "ERRORS.YOU_ARE_NOT_ALLOWED_TO_PERFORM_THIS_ACTION",
  "passwords dont match": "ERRORS.PASSWORDS_DONT_MATCH",
  "current password is missed": "ERRORS.CURRENT_PASSWORD_IS_MISSED",
  "one or more judges presented in judges_ids not found":
    "ERRORS.JUDGES_NOT_FOUND",
  "amount of teams should be at least 2": "ERRORS.AT_LEAST_TWO_TEAMS",
  "team cannot be deleted": "ERRORS.TEAM_CANNOT_BE_DELETED",
  "your account is not confirmed": "ERRORS.USER_ACCOUNT_NOT_VERIFIED",
  "user not in judge command": "ERRORS.USER_NOT_IN_JUDGE_COMMAND",
  "user doesn't have acces for this operation":
    "ERRORS.USER_DOESNT_HAVE_ACCESS_FOR_THIS_OPERATION",
  "user is not a part of event organizers":
    "ERRORS.USER_IS_NOT_A_PART_OF_EVENT_ORGANIZERS",
  "photos uploaded successfully": "ERRORS.PHOTOS_UPLOADED_SUCCESSFULLY",
  "successfully deleted photos from event":
    "ERRORS.SUCCESSFULLY_DELETED_PHOTOS_FROM_EVENT",
  "wrong match data": "ERRORS.WRONG_MATCH_DATA",
  "play off match cannot be draw": "ERRORS.PLAY_OFF_MATCH_CANNOT_BE_DRAW",
  "tournament already started": "ERRORS.TOURNAMENT_ALREADY_STARTED",
  "you are not judge or owner": "ERRORS.YOU_ARE_NOT_JUDGE_OR_OWNER",
  "this nomination event is not yours":
    "ERRORS.THIS_NOMINATION_EVENT_IS_NOT_YOURS",
  "judge not found in judges team error":
    "ERRORS.JUDGE_NOT_FOUND_IN_JUDGES_TEAM_ERROR",
  "organizer not found": "ERRORS.ORGANIZER_NOT_FOUND",
  "organizer name taken": "ERRORS.ORGANIZER_NAME_TAKEN",
  "wrong secret": "ERRORS.WRONG_SECRET",
  "secret missing": "ERRORS.SECRET_MISSING",
  "invalid role": "ERRORS.INVALID_ROLE",
  "educational institution cannot be none for non judge user":
    "ERRORS.EDUCATIONAL_INSTITUTION_CANNOT_BE_NONE_FOR_NON_JUDGE_USER",
  "user account is already confirmed": "ERRORS.USER_ACCOUNT_ALREADY_CONFIRMED",
  "token is expired": "ERRORS.TOKEN_IS_EXPIRED",
  "token has invalid signature": "ERRORS.TOKEN_HAS_INVALID_SIGNATURE",
  "hash verification failed": "ERRORS.HASH_VERIFICATION_FAILED",
  "token wasn't found": "ERRORS.TOKEN_WASN'T_FOUND",
  "processing image error": "ERRORS.PROCESSING_IMAGE_ERROR",
  "exceeded image folder size (200 MB)": "ERRORS.EXCEEDED_IMAGE_FOLDER_SIZE",
  "teams not found": "ERRORS.TEAMS_NOT_FOUND",

  getError(errorKey) {
    return i18n.t(this[errorKey]) || i18n.t("MESSAGES.ERROR");
  },
};
